#!bash

c_red=$(tput setaf 1)
c_green=$(tput setaf 2)
c_sgr0=$(tput sgr0)

parse_git_branch (){
  if git rev-parse --git-dir >/dev/null 2>&1
  then
      gitver=$(git branch 2>/dev/null| sed -n '/^\*/s/^\* //p')
  else
      return 0
  fi

  status="[$(branch_color)${gitver}${c_sgr0}]"

  git_stash="$(git stash list 2> /dev/null)"
  if [[ ! ${#git_stash} -eq 0 ]]; then
      status="${status} ☢"
  fi

  echo -e "$status "
}

branch_color (){
  if git rev-parse --git-dir >/dev/null 2>&1
  then
      color=""
  if git diff --quiet 2>/dev/null >&2
  then
      color="${c_green}"
  else
      color=${c_red}
  fi
  else
      return 0
  fi
  echo -ne "$color"
}

# shellcheck disable=2016
PS1='\W $(parse_git_branch)\$ '